"""事件词汇单一来源生成器（Phase 9 技术债修复）。

src/agent_harness/session/event.py 是事件词汇唯一真值；本脚本从它生成
web/src/generated/event-types.ts，前端 types.ts re-export 该产物。
此前前后端双处手工维护，因漂移出过 bug（tool/started vs tool/call）。

用法：
    uv run python scripts/gen_event_types.py

产物 commit 进仓库，前端构建保持纯 Node；漂移由
tests/test_event_types_generated.py 兜底（失败时提示运行上面的命令）。
"""

from __future__ import annotations

import re
from pathlib import Path

import agent_harness.session.event as event_module

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "web" / "src" / "generated" / "event-types.ts"

# 事件值形状：`域/子域[/细分]`，如 tool/call、model/delta。
# event.py 里所有匹配此形状的模块级字符串常量都视为事件词汇；
# 将来若新增同形状的非事件字符串常量，本脚本与守卫测试会暴露它。
_EVENT_VALUE_RE = re.compile(r"^[a-z]+(/[a-z_]+)+$")


def collect_vocabulary() -> tuple[list[tuple[str, str]], frozenset[str], frozenset[str]]:
    """收集事件词汇：(常量名, 值) 列表（按 event.py 定义序）+ 持久集 + 流式集。"""
    pairs = [
        (name, value)
        for name, value in vars(event_module).items()
        if not name.startswith("_")
        and isinstance(value, str)
        and _EVENT_VALUE_RE.match(value)
    ]
    return pairs, event_module.EVENT_TYPES, event_module.STREAM_ONLY_TYPES


def generate_ts() -> str:
    """渲染 event-types.ts 内容（纯函数，供 CLI 与守卫测试共用）。"""
    pairs, persistent, stream_only = collect_vocabulary()

    values = {value for _, value in pairs}
    orphans = (persistent | stream_only) - values
    if orphans:
        raise ValueError(
            f"EVENT_TYPES/STREAM_ONLY_TYPES 含没有对应模块常量的孤儿值: {sorted(orphans)}"
        )
    unregistered = values - (persistent | stream_only)
    if unregistered:
        raise ValueError(
            f"event.py 中的事件常量未入册 EVENT_TYPES/STREAM_ONLY_TYPES: {sorted(unregistered)}"
        )

    lines = [
        "// GENERATED by scripts/gen_event_types.py — DO NOT EDIT BY HAND.",
        "// Source of truth: src/agent_harness/session/event.py",
        "// Regenerate: uv run python scripts/gen_event_types.py",
        "",
        "/** All event type constants (durable + stream-only), mirroring event.py. */",
        "export const EventType = {",
    ]
    lines.extend(f"  {name}: '{value}'," for name, value in pairs)
    lines.extend(
        [
            "} as const;",
            "",
            "export type EventTypeValue = (typeof EventType)[keyof typeof EventType];",
            "",
            "/** Ephemeral streaming signals — never persisted (invariant #4: Event ≠ Diagnostic Log). */",
            "export const STREAM_ONLY_TYPES = [",
        ]
    )
    lines.extend(f"  '{value}'," for value in sorted(stream_only))
    lines.extend(["] as const;", ""])

    return "\n".join(lines)


def main() -> None:
    content = generate_ts()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
