"""事件词汇权威枚举生成器（#173 T5 / issue #178，路线 B）。

`src/agent_harness/session/event.py` 是事件词汇唯一事实源。本脚本把它的枚举面
（常量名 + 事件名 + 持久化/仅广播归属）渲染成 `docs/EVENT_VOCABULARY.md`——一份
人工可读、机器可解析的权威副本；spec `03_SESSION_EVENT_MODEL.md` §3 只引用它，
不再手工维护事件表（那张表曾漂移到 21 个名字对不上，见 #173）。

为什么不做成「解析 spec 表」（路线 A）：spec 是冻结文档，手工维护的枚举必然再次漂移；
而「生成物 + 守卫测试」是本仓库既有先例（`scripts/gen_event_types.py` +
`tests/test_event_types_generated.py`）。两条路线的取舍由 Primary Developer 选定（#178）。

用法：
    uv run python scripts/gen_event_vocabulary.py

产物 commit 进仓库；漂移由 `tests/test_event_vocabulary_generated.py` 兜底。

**格式契约**（守卫测试依赖，改格式必须同步改测试）：
- 每个事件一行，形如 ``| `CONSTANT_NAME` | `domain/name` |``，节内按事件名字母序；
- 分节标题形如 ``## 持久化（N）`` 与 ``## 仅广播（N）``，N 为该节行数。
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# 采集逻辑只留一份（复用 gen_event_types）。守卫测试按 `scripts.*` 包路径 import，
# 直接 `uv run python scripts/gen_event_vocabulary.py` 时仓库根不在 sys.path 上，故补一次。
if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.gen_event_types import collect_vocabulary

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "docs" / "EVENT_VOCABULARY.md"

# spec 侧唯一的语义来源（本生成物不解释语义，只列枚举）。
SPEC_DOC = "goal/Lightweight_Observable_Agent_Harness_Spec/docs/spec/03_SESSION_EVENT_MODEL.md"

DURABLE_HEADING = "## 持久化"
STREAM_HEADING = "## 仅广播"

# 格式契约的行形状：``| `CONST` | `domain/name` |``。写入端是 `format_row()`，
# 读取端是这条正则；两者必须一致——守卫测试的 `test_row_format_round_trips` 拿
# `format_row()` 的输出喂 `ROW_RE`，所以「改了写入忘了改读取」会红，而不是静默解析不到。
ROW_RE = re.compile(r"^\| `(?P<const>[A-Z][A-Z0-9_]*)` \| `(?P<value>[a-z][a-z0-9_]*(?:/[a-z0-9_-]+)+)` \|$")


def format_row(name: str, value: str) -> str:
    """渲染一行事件（格式契约的**唯一**写入端）。"""
    return f"| `{name}` | `{value}` |"


def _rows(pairs: list[tuple[str, str]], values: frozenset[str]) -> list[str]:
    """渲染行，按事件名字母序——查询型参考表，读者要能一眼扫到某个名字。"""
    return [
        format_row(name, value)
        for name, value in sorted(pairs, key=lambda pair: pair[1])
        if value in values
    ]


def generate_markdown() -> str:
    """渲染 EVENT_VOCABULARY.md 内容（纯函数，供 CLI 与守卫测试共用）。"""
    pairs, persistent, stream_only = collect_vocabulary()

    durable_rows = _rows(pairs, persistent)
    stream_rows = _rows(pairs, stream_only)

    # 这里查的是「渲染出来的行数 == 注册表大小」，比 `gen_event_types` 那套值集校验
    # （孤儿 / 漏册）更严一格：值集校验看不见**两个常量共用同一个事件名**（值集去重后
    # 照样相等，产物却会把这个事件列两遍）。漏渲染与重复渲染都会在这里炸。
    if len(durable_rows) != len(persistent) or len(stream_rows) != len(stream_only):
        raise ValueError(
            "渲染行数与 EVENT_TYPES/STREAM_ONLY_TYPES 不一致（漏渲染，或有常量共用了同一个事件名）："
            f"持久化 {len(durable_rows)}/{len(persistent)}，仅广播 {len(stream_rows)}/{len(stream_only)}"
        )

    total = len(durable_rows) + len(stream_rows)
    lines = [
        "<!-- GENERATED by scripts/gen_event_vocabulary.py — DO NOT EDIT BY HAND. -->",
        "",
        "# 事件词汇表（权威枚举）",
        "",
        "- **唯一事实源**：`src/agent_harness/session/event.py`",
        "- **生成命令**：`uv run python scripts/gen_event_vocabulary.py`",
        "- **漂移守卫**：`tests/test_event_vocabulary_generated.py`",
        f"- **语义 / 分层 / 历史名映射**：`{SPEC_DOC}` §3–§3.3（本表只列枚举，不解释语义）",
        "",
        f"**合计 {total} 个类型：{len(durable_rows)} 持久化 + {len(stream_rows)} 仅广播。**",
        "",
        "「持久化」= 进 append-only JSONL，`replay` / `fork` / `derive_messages` 可见；",
        "「仅广播」= 流式瞬时信号，MUST NOT 落盘（不变量 #4：Event ≠ Diagnostic Log）。",
        "",
        f"{DURABLE_HEADING}（{len(durable_rows)}）",
        "",
        "| 常量 | 事件类型 |",
        "| --- | --- |",
        *durable_rows,
        "",
        f"{STREAM_HEADING}（{len(stream_rows)}）",
        "",
        "| 常量 | 事件类型 |",
        "| --- | --- |",
        *stream_rows,
        "",
    ]
    return "\n".join(lines)


def parse_vocabulary(text: str) -> tuple[frozenset[str], frozenset[str]]:
    """从生成物解析出（持久化事件名, 仅广播事件名）两个集合。

    守卫测试用它独立复核产物内容——不依赖 `generate_markdown()` 自身的正确性。
    """
    section: str | None = None
    durable: set[str] = set()
    stream: set[str] = set()
    for line in text.splitlines():
        if line.startswith(DURABLE_HEADING):
            section = "durable"
            continue
        if line.startswith(STREAM_HEADING):
            section = "stream"
            continue
        if line.startswith(("#", "| 常量")):
            continue
        match = ROW_RE.match(line)
        if match is None:
            continue
        if section == "durable":
            durable.add(match.group("value"))
        elif section == "stream":
            stream.add(match.group("value"))
    return frozenset(durable), frozenset(stream)


def main() -> None:
    content = generate_markdown()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8", newline="\n")
    durable, stream = parse_vocabulary(content)
    print(f"wrote {OUTPUT_PATH}（{len(durable)} 持久化 + {len(stream)} 仅广播）")


if __name__ == "__main__":
    main()
