"""Session：append-only typed SessionEvent + JSONL 存储 + derive 投影。

Phase 1 完整导出：SessionEvent DTO、JsonlSessionStore、derive_messages、Session 聚合根。
"""

from agent_harness.session.context import (
    current_session_var,
    memory_injected_ids_var,
    run_context_var,
)
from agent_harness.session.cwd import cwd_event_data, session_cwd
from agent_harness.session.derive import (
    DANGLING_TOOL_CONTENT,
    derive_messages,
    detect_dangling,
)
from agent_harness.session.event import (
    AGENT_DELEGATION_FINISHED,
    AGENT_DELEGATION_STARTED,
    ARTIFACT_CREATED,
    ARTIFACT_EXTERNALIZED,
    COMPACTION_END,
    COMPACTION_START,
    CONTEXT_COMPACTED,
    CONTEXT_COMPACTION_FAILED,
    EVENT_TYPES,
    GUARD_STUCK,
    MEMORY_DEGRADED,
    MEMORY_RECALLED,
    MODEL_COMPLETED,
    MODEL_DELTA,
    MODEL_FAILED,
    MODEL_FALLBACK,
    MODEL_REQUEST,
    MODEL_STARTED,
    OPERATION_RECONCILE_REQUIRED,
    OPERATION_RECONCILED,
    PERMISSION_CHANGED,
    REASONING_COMPLETED,
    REASONING_DELTA,
    REASONING_INTERRUPTED,
    REASONING_STARTED,
    RUN_COMPLETED,
    RUN_FAILED,
    RUN_INTERRUPTED,
    RUN_PAUSED,
    RUN_RESUMED,
    RUN_STARTED,
    RUNTIME_EVENT_SCHEMA_VERSION,
    SESSION_FORKED,
    SESSION_RESUMED,
    SESSION_STARTED,
    STREAM_ONLY_TYPES,
    TASK_PLAN_UPDATED,
    TASK_PROTECTED_FACT,
    TEXT_DELTA,
    TOOL_CALL,
    TOOL_FAILURE_GUARD,
    TOOL_OUTPUT_DELTA,
    TOOL_RESULT,
    USER_MESSAGE,
    SessionEvent,
)
from agent_harness.session.header import StartedHeader
from agent_harness.session.plan import (
    PLAN_MAX_ITEMS,
    PlanItem,
    PlanState,
    PlanUpdateOutcome,
    apply_plan_update,
    derive_plan,
)
from agent_harness.session.session import Session
from agent_harness.session.store import JsonlSessionStore

__all__ = [
    "AGENT_DELEGATION_FINISHED",
    "AGENT_DELEGATION_STARTED",
    "ARTIFACT_CREATED",
    "ARTIFACT_EXTERNALIZED",
    "COMPACTION_END",
    "COMPACTION_START",
    "CONTEXT_COMPACTED",
    "CONTEXT_COMPACTION_FAILED",
    "DANGLING_TOOL_CONTENT",
    "EVENT_TYPES",
    "GUARD_STUCK",
    "MEMORY_DEGRADED",
    "MEMORY_RECALLED",
    "MODEL_COMPLETED",
    "MODEL_DELTA",
    "MODEL_FAILED",
    "MODEL_FALLBACK",
    "MODEL_REQUEST",
    "MODEL_STARTED",
    "OPERATION_RECONCILED",
    "OPERATION_RECONCILE_REQUIRED",
    "PERMISSION_CHANGED",
    "PLAN_MAX_ITEMS",
    "REASONING_COMPLETED",
    "REASONING_DELTA",
    "REASONING_INTERRUPTED",
    "REASONING_STARTED",
    "RUNTIME_EVENT_SCHEMA_VERSION",
    "RUN_COMPLETED",
    "RUN_FAILED",
    "RUN_INTERRUPTED",
    "RUN_PAUSED",
    "RUN_RESUMED",
    "RUN_STARTED",
    "SESSION_FORKED",
    "SESSION_RESUMED",
    "SESSION_STARTED",
    "STREAM_ONLY_TYPES",
    "TASK_PLAN_UPDATED",
    "TASK_PROTECTED_FACT",
    "TEXT_DELTA",
    "TOOL_CALL",
    "TOOL_FAILURE_GUARD",
    "TOOL_OUTPUT_DELTA",
    "TOOL_RESULT",
    "USER_MESSAGE",
    "JsonlSessionStore",
    "PlanItem",
    "PlanState",
    "PlanUpdateOutcome",
    "Session",
    "SessionEvent",
    "StartedHeader",
    "apply_plan_update",
    "current_session_var",
    "cwd_event_data",
    "derive_messages",
    "derive_plan",
    "detect_dangling",
    "memory_injected_ids_var",
    "run_context_var",
    "session_cwd",
]
