"""Session：append-only typed SessionEvent + JSONL 存储 + derive 投影。

Phase 1 完整导出：SessionEvent DTO、JsonlSessionStore、derive_messages、Session 聚合根。
"""

from agent_harness.session.context import run_context_var
from agent_harness.session.derive import (
    DANGLING_TOOL_CONTENT,
    derive_messages,
    detect_dangling,
)
from agent_harness.session.event import (
    AGENT_DELEGATION_FINISHED,
    AGENT_DELEGATION_STARTED,
    ARTIFACT_CREATED,
    ARTIFACT_EXTERNALIZED,
    COMPACTION_END,
    COMPACTION_START,
    CONTEXT_COMPACTED,
    EVENT_TYPES,
    MEMORY_DEGRADED,
    MODEL_COMPLETED,
    MODEL_DELTA,
    MODEL_FAILED,
    MODEL_FALLBACK,
    MODEL_STARTED,
    OPERATION_RECONCILE_REQUIRED,
    REASONING_COMPLETED,
    REASONING_DELTA,
    REASONING_INTERRUPTED,
    REASONING_STARTED,
    RUN_COMPLETED,
    RUN_FAILED,
    RUN_STARTED,
    RUNTIME_EVENT_SCHEMA_VERSION,
    SESSION_FORKED,
    SESSION_RESUMED,
    SESSION_STARTED,
    STREAM_ONLY_TYPES,
    TEXT_DELTA,
    TOOL_CALL,
    TOOL_FAILURE_GUARD,
    TOOL_OUTPUT_DELTA,
    TOOL_RESULT,
    USER_MESSAGE,
    SessionEvent,
)
from agent_harness.session.session import Session
from agent_harness.session.store import JsonlSessionStore

__all__ = [
    "AGENT_DELEGATION_FINISHED",
    "AGENT_DELEGATION_STARTED",
    "ARTIFACT_CREATED",
    "ARTIFACT_EXTERNALIZED",
    "COMPACTION_END",
    "COMPACTION_START",
    "CONTEXT_COMPACTED",
    "DANGLING_TOOL_CONTENT",
    "EVENT_TYPES",
    "MEMORY_DEGRADED",
    "MODEL_COMPLETED",
    "MODEL_DELTA",
    "MODEL_FAILED",
    "MODEL_FALLBACK",
    "MODEL_STARTED",
    "OPERATION_RECONCILE_REQUIRED",
    "REASONING_COMPLETED",
    "REASONING_DELTA",
    "REASONING_INTERRUPTED",
    "REASONING_STARTED",
    "RUNTIME_EVENT_SCHEMA_VERSION",
    "RUN_COMPLETED",
    "RUN_FAILED",
    "RUN_STARTED",
    "SESSION_FORKED",
    "SESSION_RESUMED",
    "SESSION_STARTED",
    "STREAM_ONLY_TYPES",
    "TEXT_DELTA",
    "TOOL_CALL",
    "TOOL_FAILURE_GUARD",
    "TOOL_OUTPUT_DELTA",
    "TOOL_RESULT",
    "USER_MESSAGE",
    "JsonlSessionStore",
    "Session",
    "SessionEvent",
    "derive_messages",
    "detect_dangling",
    "run_context_var",
]

